### ISSUE TITLE
Missing q parameter for changes.queryChanges()

### ISSUE THREAD

**Issue by felipecrs** [gerritkit/client#19]
I'm building a VS Code extension for Gerrit, and I'm thinking about using `@gerritkit/native` to simplify the work. However, I noticed that the parameters are not properly being handled by the `generator`.

For example, the `queryChanges()` endpoint was supposed to accept a parameter called `q`:

https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#list-changes

Currently, it does not accept any, and therefore it returns all the changes.

I wonder if it would be a good idea to always allow users to specify any parameters as well, such as:

```js
async queryChanges(options = { params: {} }) {
  return axios({
    method: 'GET',
    url: `${baseUrl}/changes/`,
    auth,
    params: options.params,
  }).then(({ data }) => parseGerritResponse(data) as TChangeInfo[])
},
```

**Comment by pismenskiy** [comment]
Hi. Sounds reasonable, we'll try to fix the problem. Thanks for your feedback

**Comment by felipecrs** [comment]
This is awesome! Thank you so much!
